import {
  Activity, Atom, Bell, Boxes, Braces, Database, FlaskConical, Gauge, LayoutDashboard,
  LineChart, Newspaper, Scale, Settings, ShieldAlert, Sparkles, Wallet, Zap, FileSpreadsheet,
  Radio, Cpu, BrainCircuit, Network, Binary, Orbit, Globe, BarChart3, Bot, Layers, Lock, Dna, Compass,
} from "lucide-react";

export type NavItem = { label: string; to: string; icon: React.ElementType; badge?: string; tone?: "pos" | "warn" | "neg" };

export const NAV_GROUPS: { title: string; items: NavItem[] }[] = [
  {
    title: "Workspace",
    items: [
      { label: "Overview", to: "/dashboard", icon: LayoutDashboard },
      { label: "Markets", to: "/markets", icon: LineChart },
      { label: "Research", to: "/research", icon: Newspaper },
      { label: "Alpha Lab", to: "/research/alpha", icon: FlaskConical },
      { label: "Portfolio", to: "/portfolio", icon: Wallet },
      { label: "Zerodha Live", to: "/integrations/zerodha", icon: Radio, badge: "LIVE", tone: "pos" },
      { label: "CSV Analysis", to: "/portfolio/analysis", icon: FileSpreadsheet },
      { label: "Optimization", to: "/portfolio/optimizer", icon: Scale },
      { label: "Risk", to: "/risk", icon: ShieldAlert },
      { label: "Backtesting", to: "/backtest", icon: Atom },
      { label: "Execution", to: "/execution", icon: Zap },
      { label: "Models", to: "/models", icon: Boxes },
      { label: "MARL Swarm", to: "/marl", icon: Cpu, badge: "v22", tone: "pos" },
      { label: "DL Copilot", to: "/dl-trading", icon: BrainCircuit, badge: "v23", tone: "pos" },
      { label: "Causal AI", to: "/causal-ai", icon: Network, badge: "v24", tone: "pos" },
      { label: "Sovereign AI", to: "/sovereign-ai", icon: Binary, badge: "v25", tone: "pos" },
      { label: "TDA & Quantum", to: "/tda-quantum", icon: Orbit, badge: "v26", tone: "pos" },
      { label: "Universal 5K", to: "/universal-market", icon: Globe, badge: "v27", tone: "pos" },
      { label: "Visual & DL-10", to: "/visual-dl10", icon: BarChart3, badge: "v29", tone: "pos" },
      { label: "Autonomous AI", to: "/autonomous-v30", icon: Bot, badge: "v30", tone: "pos" },
      { label: "World Model & EMS", to: "/world-model-v31", icon: Layers, badge: "v31", tone: "pos" },
      { label: "Post-Quantum & Photonic", to: "/post-quantum-v32", icon: Lock, badge: "v32", tone: "pos" },
      { label: "Sovereign Memristive", to: "/sovereign-v33", icon: Cpu, badge: "v33", tone: "pos" },
      { label: "Sovereign DNA & Quantum", to: "/sovereign-v34", icon: Dna, badge: "v34", tone: "pos" },
      { label: "Singularity & Entangled AI", to: "/singularity-v35", icon: Sparkles, badge: "v35", tone: "pos" },
      { label: "Multiverse & BCI Capital", to: "/multiverse-v36", icon: Orbit, badge: "v36", tone: "cyan" },
      { label: "Omni-Sovereign v37", to: "/omni-v37", icon: Zap, badge: "v37", tone: "pos" },
      { label: "Omni-Singularity v38", to: "/omni-v38", icon: Compass, badge: "v38", tone: "cyan" },
      { label: "Omni-Singularity v39", to: "/omni-v39", icon: Scale, badge: "v39", tone: "pos" },
      { label: "Omni-Singularity v40", to: "/omni-v40", icon: Atom, badge: "v40", tone: "purple" },
      { label: "Data", to: "/data", icon: Database },

      { label: "AI Copilot", to: "/copilot", icon: Sparkles, badge: "AI", tone: "pos" },
    ],
  },
  {
    title: "System",
    items: [
      { label: "Alerts", to: "/alerts", icon: Bell, badge: "2", tone: "warn" },
      { label: "Monitoring", to: "/monitoring", icon: Activity },
      { label: "Settings", to: "/settings", icon: Settings },
    ],
  },
];

export const ROUTE_TITLES: Record<string, string[]> = {
  "/dashboard": ["Workspace", "Overview"],
  "/markets": ["Workspace", "Markets"],
  "/research": ["Workspace", "Research", "News & Sentiment"],
  "/research/alpha": ["Workspace", "Research", "Alpha Lab"],
  "/portfolio": ["Workspace", "Portfolio"],
  "/integrations/zerodha": ["Workspace", "Integrations", "Zerodha Kite Connect"],
  "/portfolio/analysis": ["Workspace", "Portfolio", "CSV Analysis"],
  "/portfolio/optimizer": ["Workspace", "Portfolio", "Optimizer"],
  "/risk": ["Workspace", "Risk Command Center"],
  "/backtest": ["Workspace", "Backtesting Studio"],
  "/execution": ["Workspace", "Execution"],
  "/models": ["Workspace", "Model Monitoring"],
  "/marl": ["Workspace", "MARL Swarm", "L2/L3 Microstructure"],
  "/dl-trading": ["Workspace", "DL Copilot", "Multi-Modal Trading Studio"],
  "/causal-ai": ["Workspace", "Causal AI", "ST-GNN & Agentic Studio"],
  "/sovereign-ai": ["Workspace", "Sovereign AI", "Neuromorphic & zk-PoS Studio"],
  "/tda-quantum": ["Workspace", "TDA & Quantum", "Topological & MPS Studio"],
  "/universal-market": ["Workspace", "Universal Market", "NSE/BSE 5K & Sharded Cluster"],
  "/visual-dl10": ["Workspace", "Visual & DL-10", "Rate Statements, Grading & 10-Layer Recommender"],
  "/autonomous-v30": ["Workspace", "Autonomous AI", "OCR GAT, 100k Monte Carlo & Order Slicer"],
  "/world-model-v31": ["Workspace", "World Model & EMS", "L2/L3 World Model, Self-Healing SmartNIC & zk-Audit"],
  "/post-quantum-v32": ["Workspace", "Post-Quantum & Photonic", "NIST Dilithium/Kyber, Photonic Tensor & zk-DvP"],
  "/sovereign-v33": ["Workspace", "Sovereign Memristive & BFT", "Memristor VMM, zk-FLDG, Immune AIS & BFT Swarm"],
  "/sovereign-v34": ["Workspace", "Sovereign DNA & Topological", "DNA Storage, tQNPU Anyon Braiding, CBDC & Epigenetic"],
  "/singularity-v35": ["Workspace", "Singularity & Entangled AI", "Diffusion World Model, CV-QKD OMS, CNT-EMS & Constitutional AI"],
  "/multiverse-v36": ["Workspace", "Multiverse & BCI Capital", "Multi-Planetary DTN, BCI Telemetry, AdS/CFT Risk & zk-PoC"],
  "/omni-v37": ["Workspace", "Omni-Sovereign & zk-MJRC", "Fractional Calculus, Photonic QRNG, Swarm Evolution & Multi-Jurisdictional Consensus"],
  "/omni-v38": ["Workspace", "Omni-Singularity & TQFT", "Topological Field Theory, 100k+ Qubit QUBO, Wetware DNA & zk-HMSCG"],
  "/omni-v39": ["Workspace", "Omni-Singularity & QTSFT", "Calabi-Yau Mirror, Wetware Organoid, zk-MCSRM & Constitutional AI"],
  "/omni-v40": ["Workspace", "Omni-Singularity & Multiverse", "11D String Multiverse, IIT 4.0 Φ-Core, ZPE QPU & zk-TSCCM"],
  "/data": ["Workspace", "Data Quality Center"],
  "/copilot": ["Workspace", "Quant Copilot"],
  "/alerts": ["System", "Alerts"],
  "/monitoring": ["System", "Monitoring"],
  "/settings": ["System", "Settings"],
  "/profile": ["Account", "Profile"],
};

export type Command = { id: string; label: string; hint?: string; group: string; to?: string; action?: string; icon: React.ElementType; keywords?: string };

export const COMMANDS: Command[] = [
  { id: "c1", label: "Open Overview", group: "Navigation", to: "/dashboard", icon: LayoutDashboard, keywords: "dashboard home command center" },
  { id: "c-marl", label: "Open MARL Swarm & L2/L3 Microstructure Studio", group: "Navigation", to: "/marl", icon: Cpu, keywords: "marl reinforcement learning ppo sac l2 l3 microprice obi v22" },
  { id: "c-dl", label: "Open Deep Learning & AI Trading Copilot Studio", group: "Navigation", to: "/dl-trading", icon: BrainCircuit, keywords: "dl deep learning tft tcn sac vae copilot multimodal trading v23" },
  { id: "c-causal", label: "Open Causal AI & ST-GNN Agentic Studio", group: "Navigation", to: "/causal-ai", icon: Network, keywords: "causal pearl do-calculus gnn st-gnn react tot ptp mps tensor v24" },
  { id: "c-sovereign", label: "Open Sovereign AI & Neuromorphic Studio", group: "Navigation", to: "/sovereign-ai", icon: Binary, keywords: "sovereign lnn neuromorphic ode zk pos solvency federated wasm v25" },
  { id: "c-tda", label: "Open TDA & Quantum Tensor Studio", group: "Navigation", to: "/tda-quantum", icon: Orbit, keywords: "tda topological homology betti mps tensor z3 darkpool spsc v26" },
  { id: "c-univ", label: "Open Universal Market Studio (5,000+ Stocks)", group: "Navigation", to: "/universal-market", icon: Globe, keywords: "universal market universe 5k bse nse zerodha sharded cluster v27" },
  { id: "c-v29", label: "Open Visual Analytics & DL-10 Studio (v29)", group: "Navigation", to: "/visual-dl10", icon: BarChart3, keywords: "visual analytics dl-10 rate wacc dscr grading histogram heatmap waterfall v29" },
  { id: "c-v30", label: "Open Autonomous AI Execution Studio (v30)", group: "Navigation", to: "/autonomous-v30", icon: Bot, keywords: "autonomous rebalance ocr gat monte carlo order slicer twap vwap pov v30" },
  { id: "c-v31", label: "Open World Model & Self-Healing EMS Studio (v31)", group: "Navigation", to: "/world-model-v31", icon: Layers, keywords: "world model ems smartnic zk-audit counterfactual do-calculus l2 l3 orderbook failover v31" },
  { id: "c-v32", label: "Open Post-Quantum Security & Photonic Causal Studio (v32)", group: "Navigation", to: "/post-quantum-v32", icon: Lock, keywords: "post-quantum pqc dilithium kyber photonic optical mzi zk-dvp atomic settlement causal dag v32" },
  { id: "c-v33", label: "Open Sovereign Memristive & BFT Risk Swarm Studio (v33)", group: "Navigation", to: "/sovereign-v33", icon: Cpu, keywords: "sovereign memristor vmm spde heston zk-fldg federated liquidity immune digital antibody bft swarm consensus v33" },
  { id: "c-v34", label: "Open Sovereign DNA Storage & Topological Quantum Studio (v34)", group: "Navigation", to: "/sovereign-v34", icon: Dna, keywords: "sovereign dna storage archival biological tqnpu majorana anyon braiding cbdc einr eusd eeur epigenetic marl v34" },
  { id: "c-v35", label: "Open Synthetic Market Singularity & Entangled OMS Studio (v35)", group: "Navigation", to: "/singularity-v35", icon: Sparkles, keywords: "singularity synthetic dit diffusion world model entangled qkd cv-qkd bell state cnt carbon nanotube constitutional ai p-breach v35" },
  { id: "c-v36", label: "Open Multi-Planetary Sovereign Capital & BCI Studio (v36)", group: "Navigation", to: "/multiverse-v36", icon: Orbit, keywords: "multiverse planetary dtn relativistic bci eeg fnirs stress ads cft hyperbolic wormhole zk-poc halo2 causal do-calculus v36" },
  { id: "c-v37", label: "Open Omni-Sovereign Fractional Calculus, Photonic QRNG & zk-MJRC Studio (v37)", group: "Navigation", to: "/omni-v37", icon: Zap, keywords: "v37 omni fractional calculus caputo hurst qrng photonic laser vacuum bio swarm z3 smt zk-mjrc regulatory sebi sec esma mas" },
  { id: "c-v38", label: "Open Omni-Singularity TQFT, 100k+ Qubit Annealer & zk-HMSCG Studio (v38)", group: "Navigation", to: "/omni-v38", icon: Compass, keywords: "v38 omni singularity tqft chern-simons gauge manifold qubo quantum transmon annealer dna wetware organoid zk-hmscg fhe-ckks halo2 sebi sec esma mas" },
  { id: "c-v39", label: "Open Omni-Singularity QTSFT, Wetware Organoid & zk-MCSRM Studio (v39)", group: "Navigation", to: "/omni-v39", icon: Scale, keywords: "v39 omni singularity qtsft calabi-yau mirror symmetry wetware organoid mea stdp zk-mcsrm ml-kem ml-dsa lean4 z3 smt constitutional ai p-breach" },
  { id: "c-v40", label: "Open Omni-Singularity String Multiverse, Φ-Core & ZPE Studio (v40)", group: "Navigation", to: "/omni-v40", icon: Atom, keywords: "v40 omni singularity string multiverse 11d m-theory non-commutative phi-core iit 4.0 zpe casimir photonic attosecond zk-tsccm sebi sec esma bis" },



  { id: "c2", label: "Open Portfolio Risk", group: "Navigation", to: "/risk", icon: ShieldAlert, keywords: "var cvar beta stress" },
  { id: "c3", label: "Open Alpha Lab", group: "Navigation", to: "/research/alpha", icon: FlaskConical, keywords: "factor momentum value quality" },
  { id: "c4", label: "Open Portfolio Optimizer", group: "Navigation", to: "/portfolio/optimizer", icon: Scale, keywords: "efficient frontier constraints" },
  { id: "c5", label: "Open Backtesting Studio", group: "Navigation", to: "/backtest", icon: Atom, keywords: "simulate strategy equity curve" },
  { id: "c6", label: "Open Model Monitoring", group: "Navigation", to: "/models", icon: Boxes, keywords: "mlops drift xgb finbert" },
  { id: "c7", label: "Open Data Quality Center", group: "Navigation", to: "/data", icon: Database, keywords: "feeds coverage freshness" },
  { id: "c8", label: "Open Quant Copilot", group: "Navigation", to: "/copilot", icon: Sparkles, keywords: "ai assistant research" },
  { id: "c9", label: "Open Markets", group: "Navigation", to: "/markets", icon: LineChart, keywords: "indices heatmap breadth" },
  { id: "c10", label: "Open Execution Blotter", group: "Navigation", to: "/execution", icon: Zap, keywords: "orders fills slippage algo" },
  { id: "c11", label: "AutoQuant Symbolic Alpha Engine", group: "Navigation", to: "/research/alpha", icon: FlaskConical, keywords: "autoquant symbolic alpha genetic ast formula expression" },
  { id: "c12", label: "Causal Macro Scenario Simulator (SVAR)", group: "Navigation", to: "/risk", icon: ShieldAlert, keywords: "causal macro graph shock svar interest rate oil impulse" },
  { id: "c13", label: "Avellaneda-Stoikov Market-Maker & RFQ Bridge", group: "Navigation", to: "/execution", icon: Zap, keywords: "avellaneda stoikov inventory spread rfq institutional zk" },
  { id: "c14", label: "Open Zerodha Live Demat & Ticker", group: "Navigation", to: "/integrations/zerodha", icon: Radio, keywords: "zerodha kite connect nse bse live demat holdings ticks market depth" },

  { id: "a1", label: "Run Backtest", hint: "Momentum-Quality Composite", group: "Actions", to: "/backtest", action: "run-backtest", icon: Atom },
  { id: "a2", label: "Optimize Portfolio", hint: "Max Sharpe under constraints", group: "Actions", to: "/portfolio/optimizer", action: "optimize", icon: Scale },
  { id: "a3", label: "Show today's alpha", hint: "Ranked cross-sectional signals", group: "Actions", to: "/dashboard", icon: Gauge },
  { id: "a4", label: "Explain drawdown", hint: "Ask Copilot", group: "Actions", to: "/copilot", action: "ask:Explain the March drawdown", icon: Sparkles },
  { id: "a5", label: "Compare portfolio vs NIFTY", hint: "Ask Copilot", group: "Actions", to: "/copilot", action: "ask:Compare portfolio vs NIFTY 50 YTD", icon: Sparkles },
  { id: "a6", label: "Run stress test", hint: "Scenario library", group: "Actions", to: "/risk", action: "stress", icon: ShieldAlert },
  { id: "a7", label: "Toggle environment", hint: "Paper ⇄ Live", group: "Actions", action: "toggle-env", icon: Braces },
];
