import { useEffect, useState } from "react";
import { Save, ShieldCheck } from "lucide-react";
import { PageHeader } from "../components/layout/AppShell";
import { Badge, Button, Panel } from "../components/ui";
import { useAuth } from "../lib/auth";

type ProfileData = { full_name: string; email: string; title: string; desk: string; preferences: { risk_profile?: string; report_focus?: string; base_currency?: string } };
export default function Profile() {
  const { signOut, refresh } = useAuth(); const [data, setData] = useState<ProfileData | null>(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/v1/profile", { credentials: "include" }).then(r => r.ok ? r.json() : Promise.reject()).then(setData).catch(() => setMessage("Unable to load profile.")); }, []);
  const update = (key: keyof ProfileData, value: string) => setData(d => d ? { ...d, [key]: value } : d);
  async function save() { if (!data) return; setSaving(true); setMessage(""); const response = await fetch("/api/v1/profile", { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); if (response.ok) { setData(await response.json()); await refresh(); setMessage("Profile and custom research preferences saved."); } else setMessage((await response.json()).detail || "Unable to save profile."); setSaving(false); }
  if (!data) return <div className="text-[12px] text-txt-muted">Loading profile…</div>;
  return <><PageHeader title="Profile & Research Preferences" sub="Configure your desk identity and defaults that shape CSV portfolio research output." meta={<Badge tone="pos" dot>SECURE PROFILE</Badge>} /><div className="grid gap-3 xl:grid-cols-2"><Panel level={3} title="Profile"><div className="space-y-3"><Input label="Full name" value={data.full_name} onChange={v => update("full_name", v)} /><Input label="Email" value={data.email} disabled /><Input label="Role / title" value={data.title} onChange={v => update("title", v)} /><Input label="Desk" value={data.desk} onChange={v => update("desk", v)} /></div></Panel><Panel level={3} title="Custom research defaults" sub="Used as your starting configuration for future portfolio analysis."><div className="space-y-3"><Select label="Risk posture" value={data.preferences.risk_profile ?? "Balanced"} options={["Conservative", "Balanced", "Growth", "Aggressive"]} onChange={v => setData(d => d ? { ...d, preferences: { ...d.preferences, risk_profile: v } } : d)} /><Select label="Report emphasis" value={data.preferences.report_focus ?? "Risk and concentration"} options={["Risk and concentration", "Performance attribution", "Factor exposure", "Tax and turnover"]} onChange={v => setData(d => d ? { ...d, preferences: { ...d.preferences, report_focus: v } } : d)} /><Select label="Base currency" value={data.preferences.base_currency ?? "INR"} options={["INR", "USD", "EUR", "GBP"]} onChange={v => setData(d => d ? { ...d, preferences: { ...d.preferences, base_currency: v } } : d)} /><p className="rounded-[6px] border border-line-subtle bg-surface-2 p-2.5 text-[10.5px] leading-relaxed text-txt-secondary"><ShieldCheck size={12} className="mr-1 inline text-acc" />Preferences do not override your uploaded CSV data; they set the reporting context only.</p></div></Panel></div><div className="mt-4 flex flex-wrap gap-2"><Button variant="primary" icon={Save} loading={saving} onClick={save}>Save profile</Button><Button variant="outline" onClick={signOut}>Sign out</Button>{message && <span className="self-center text-[11px] text-txt-secondary">{message}</span>}</div></>;
}
function Input({ label, value, onChange, disabled }: { label: string; value: string; onChange?: (v: string) => void; disabled?: boolean }) { return <label className="block"><span className="label-xs text-txt-muted">{label}</span><input disabled={disabled} value={value} onChange={e => onChange?.(e.target.value)} className="mt-1.5 w-full rounded-[6px] border border-line bg-surface-2 px-3 py-2 text-[12px] text-txt-primary disabled:opacity-60" /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (v: string) => void }) { return <label className="block"><span className="label-xs text-txt-muted">{label}</span><select value={value} onChange={e => onChange(e.target.value)} className="mt-1.5 w-full rounded-[6px] border border-line bg-surface-2 px-3 py-2 text-[12px] text-txt-primary">{options.map(o => <option key={o}>{o}</option>)}</select></label>; }
